package CapstoneTests;

import org.example.CapstoneProject.service.JwtService;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

// -------------------------------------------------------------------------
// Tests the JwtService.
//
// These tests verify:
// - JWT generation
// - JWT validation
// - Username extraction
// - Rejection of invalid tokens
// -------------------------------------------------------------------------
public class JwtServiceTest {

    // ---------------------------------------------------------------------
    // Tests that a generated JWT is not null or blank.
    // ---------------------------------------------------------------------
    @Test
    public void generateToken_returnsToken() {

        // Create the service directly.
        var jwtService = new JwtService();

        // Generate a token for a test username.
        String token = jwtService.generateToken("sharbel343");

        // Verify that a token was generated.
        assertNotNull(token);
        assertFalse(token.isBlank());
    }

    // ---------------------------------------------------------------------
    // Tests that a JWT generated by JwtService passes validation.
    // ---------------------------------------------------------------------
    @Test
    public void validateToken_withValidToken_returnsTrue() {

        // Create the service directly.
        var jwtService = new JwtService();

        // Generate a valid token.
        String token = jwtService.generateToken("sharbel343");

        // Verify that the generated token is valid.
        assertTrue(jwtService.validateToken(token));
    }

    // ---------------------------------------------------------------------
    // Tests that the username can be extracted from the JWT subject claim.
    // ---------------------------------------------------------------------
    @Test
    public void extractUsername_withValidToken_returnsUsername() {

        // Create the service directly.
        var jwtService = new JwtService();

        // Generate a token for a known username.
        String token = jwtService.generateToken("sharbel343");

        // Extract the username from the token.
        String username = jwtService.extractUsername(token);

        // Verify that the extracted username matches the original username.
        assertEquals("sharbel343", username);
    }

    // ---------------------------------------------------------------------
    // Tests that a malformed JWT is rejected.
    // ---------------------------------------------------------------------
    @Test
    public void validateToken_withInvalidToken_returnsFalse() {

        // Create the service directly.
        var jwtService = new JwtService();

        // Create an invalid JWT string.
        String invalidToken = "this.is.not-a-valid-jwt";

        // Verify that the invalid token is rejected.
        assertFalse(jwtService.validateToken(invalidToken));
    }

    @Test
    public void validateToken_withTamperedToken_returnsFalse() {
        // Create the service directly.
        var jwtService = new JwtService();

        // Generate a valid token.
        String token = jwtService.generateToken("testUser");

        // Tamper with the payload to make it invalid.
        String[] parts = token.split("\\.");
        String payload = parts[1];

        // Replace the first character of the payload with a different character.
        char replacement = payload.charAt(0) == 'A' ? 'B' : 'A';
        // Remove the first character of the payload.
        String tamperedPayload = replacement + payload.substring(1);
        // Reconstruct the token with the tampered payload.
        String tamperedToken = parts[0] + "." + tamperedPayload + "." + parts[2];
        // Verify that the tampered token is rejected.
        assertFalse(jwtService.validateToken(tamperedToken));
    }
}