@file:Suppress("PackageName")
package CapstoneTests
import com.nimbusds.jose.JWSAlgorithm
import com.nimbusds.jose.JWSHeader
import com.nimbusds.jose.crypto.MACSigner
import com.nimbusds.jwt.JWTClaimsSet
import com.nimbusds.jwt.SignedJWT
import org.example.CapstoneProject.service.JwtService
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.util.Date

// -------------------------------------------------------------------------
// Fake secret used only by automated tests.
//
// This value has no relationship to the real JWT_SECRET and is safe
// to keep inside the test source code.
//
// It is intentionally long enough to support both HS256 and HS384.
// -------------------------------------------------------------------------
private const val TEST_SECRET =
    "ThisIsOnlyATestSecretAndItIsLongEnoughForHS384Signing123456789"

// -------------------------------------------------------------------------
// Tests the JwtService.
//
// These tests verify:
// - JWT generation
// - JWT validation
// - Username extraction
// - Rejection of invalid tokens
// - Rejection of tampered tokens
// - Rejection of tokens that use a different signing algorithm
// -------------------------------------------------------------------------
class JwtServiceTest {

    // ---------------------------------------------------------------------
    // Tests that a generated JWT is not null or blank.
    // ---------------------------------------------------------------------
    @Test
    fun generateToken_returnsToken() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)
        // Generate a token for a test username.
        val token = jwtService.generateToken("sharbel343")

        // Verify that a token was generated.
        assertNotNull(token)
        // Verify that the generated token is not blank.
        assertFalse(token.isBlank())
    }

    // ---------------------------------------------------------------------
    // Tests that a JWT generated by JwtService passes validation.
    // ---------------------------------------------------------------------
    @Test
    fun validateToken_withValidToken_returnsTrue() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)

        // Generate a valid token.
        val token = jwtService.generateToken("sharbel343")

        // Verify that the generated token is valid.
        assertTrue(jwtService.validateToken(token))
    }

    // ---------------------------------------------------------------------
    // Tests that the username can be extracted from the JWT subject claim.
    // ---------------------------------------------------------------------
    @Test
    fun extractUsername_withValidToken_returnsUsername() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)
        // Generate a token for a known username.
        val token = jwtService.generateToken("sharbel343")
        // Extract the username from the token.
        val username = jwtService.extractUsername(token)

        // Verify that the extracted username matches the original username.
        assertEquals("sharbel343", username)
    }

    // ---------------------------------------------------------------------
    // Tests that a malformed JWT is rejected.
    // ---------------------------------------------------------------------
    @Test
    fun validateToken_withInvalidToken_returnsFalse() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)
        // Create an invalid JWT string.
        val invalidToken = "this.is.not-a-valid-jwt"

        // Verify that the invalid token is rejected.
        assertFalse(jwtService.validateToken(invalidToken))
    }

    // ---------------------------------------------------------------------
    // Tests that changing the payload of a valid JWT invalidates the token.
    // ---------------------------------------------------------------------
    @Test
    fun validateToken_withTamperedToken_returnsFalse() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)
        // Generate a valid token.
        val token = jwtService.generateToken("testUser")
        // Separate the JWT into header, payload and signature sections.
        val parts = token.split(Regex("\\."))
        // Read the encoded JWT payload section.
        val payload = parts[1]

        // Replace the first character of the payload with a different value.
        val replacement = if (payload[0] == 'A') 'B' else 'A'

        // Create a modified payload while keeping the remaining characters.
        val tamperedPayload = replacement + payload.substring(1)

        // Reconstruct the token using the modified payload
        // while keeping the original header and signature.
        val tamperedToken = "${parts[0]}.$tamperedPayload.${parts[2]}"

        // Verify that the changed token is rejected.
        assertFalse(jwtService.validateToken(tamperedToken))
    }

    // ---------------------------------------------------------------------
    // Tests that JwtService rejects a correctly signed JWT when it uses
    // HS384 instead of the required HS256 algorithm.
    //
    // The same test secret is used by both JwtService and the HS384 signer.
    // Therefore, the token is rejected because of the algorithm policy
    // rather than because a different secret was used.
    // ---------------------------------------------------------------------
    @Test
    fun validateToken_withDifferentAlgorithm_returnsFalse() {
        // Create the service using the dedicated test secret.
        val jwtService = JwtService(TEST_SECRET)

        // Store the current time.
        val now = Date()
        // Create an expiration time one minute in the future.
        val expiration = Date(now.time + 60_000)

        // Create valid JWT claims.
        val claims = JWTClaimsSet.Builder()
            .subject("testUser")
            .issueTime(now)
            .expirationTime(expiration)
            .build()

        // Create a JWT using HS384 instead of the required HS256 algorithm.
        val signedJWT = SignedJWT(
            JWSHeader(JWSAlgorithm.HS384),
            claims
        )

        // Sign the HS384 token using exactly the same test secret
        // used by JwtService.
        signedJWT.sign(
            MACSigner(TEST_SECRET)
        )

        // Convert the correctly signed HS384 JWT to compact format.
        val token = signedJWT.serialize()

        // Verify that the token is rejected because HS256 is required.
        assertFalse(
            jwtService.validateToken(token)
        )
    }
}